---
- name: Check basic connectivity and system info
  hosts: all
  gather_facts: true
  tasks:
    - name: Ping the Raspberry Pi
      ansible.builtin.ping:

    - name: Get system uptime
      ansible.builtin.command: uptime
      register: uptime_output
      changed_when: false

    - name: Get Python version
      ansible.builtin.command: python3 --version
      register: python_version
      changed_when: false

    - name: Display architecture
      ansible.builtin.debug:
        var: ansible_architecture

    - name: Display release
      ansible.builtin.debug:
        var: ansible_distribution_release

    - name: Display uptime
      ansible.builtin.debug:
        var: uptime_output.stdout

    - name: Display Python version
      ansible.builtin.debug:
        var: python_version.stdout
